name = "hello/world"        # {organisation}/{project}
version = "0.170.202311"
license = "Apache-2.0"
description = "Aiken contracts for project 'hello/world'"

[repository]                # additional structured information on a project to show in generated documentation
user = "ariady-putra"
project = "world"
platform = "github"         # `github`, `gitlab` or `bitbucket`

[[dependencies]]            # `aiken packages`
name = "aiken-lang/stdlib"
version = "1.7.0"
source = "github"           # `github`, `gitlab` or `bitbucket`
